--Select all data info--
SELECT *
FROM Chocolate_Sales

--Total Sales By Country and Product--
SELECT 
Country,
[Product],
Amount * Boxes_Shipped AS Total_Sales
FROM Chocolate_Sales

--Total Revenue by Country--
SELECT
Country,
SUM(Amount * Boxes_shipped) AS Total_Revenue
FROM
Chocolate_Sales
GROUP BY Country
Order by Total_Revenue DESC

--Cost Per Sale where Country is USA and Product is Rasberry Choco--
SELECT 
Country,
[Product],
Amount * Boxes_shipped AS Cost_Per_Sale
FROM
Chocolate_Sales
WHERE Country = 'USA' AND [Product] = 'Raspberry Choco'
ORDER BY Cost_Per_Sale DESC

--Top 10 Sales Person and Product where the country is USA--
--and Total Revenue is less than 3million
SELECT
TOP(10)
Sales_Person,
[Product],
SUM(Amount * Boxes_shipped) AS Total_Revenue
FROM
Chocolate_Sales
WHERE Country = 'USA'
GROUP BY Sales_Person, [Product]
HAVING SUM(Amount * Boxes_shipped) < 3000000
Order by Total_Revenue DESC


--Top 5 Sales Person and Product where the country is USA--
--and Total Revenue is greater than 3million
SELECT
TOP(5)
Sales_Person,
[Product],
SUM(Amount * Boxes_shipped) AS Total_Revenue
FROM
Chocolate_Sales
WHERE Country = 'USA'
GROUP BY Sales_Person, [Product]
HAVING SUM(Amount * Boxes_shipped) > 3000000
Order by Total_Revenue DESC

--Cost per product where product is "Milk Bars"--
SELECT 
[Product],
Amount * Boxes_Shipped AS Total_Sales_Per_Product
FROM Chocolate_Sales
WHERE [Product] = 'Milk Bars'

--Total Revenue for Product with Milk Bars--
SELECT 
Sales_Person,
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM Chocolate_Sales
WHERE [Product] = 'Milk Bars'
GROUP BY 
Sales_Person,[Product]

--Total Revenue for Sales Person with "a" in their names--
SELECT 
Sales_Person,
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM Chocolate_Sales
WHERE Sales_Person like '%a%'
GROUP BY 
Sales_Person,[Product]

--Average Boxes shipped per Product & Sales Person--
SELECT 
Sales_Person,
[Product],
AVG(Amount * Boxes_Shipped) AS Cost_Per_Product
FROM Chocolate_Sales
GROUP BY 
Sales_Person,[Product]

--Average Boxes shipped per Product--
SELECT 
[Product],
AVG(Boxes_Shipped) AS AVG_Boxes_Per_Product
FROM Chocolate_Sales
GROUP BY 
[Product]

--Average Cost per Product--
SELECT 
[Product],
AVG(Amount * Boxes_Shipped) AS AVG_Cost_Per_Product
FROM Chocolate_Sales
GROUP BY 
[Product]

--Cost per product greater than 50000--
SELECT 
[Product],
Amount * Boxes_Shipped AS Cost_Per_Product
FROM Chocolate_Sales
GROUP BY 
[Product],Amount * Boxes_Shipped
Having Amount * Boxes_Shipped <= 50000

--Average amount per Product--
SELECT 
[Product],
AVG(Amount) AS AVG_Amount
FROM Chocolate_Sales
GROUP BY 
[Product]


--Yearly and Monthly Sales Revenue--
SELECT
YEAR(Date) AS Year,
MONTH(Date) AS Month,
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_Sales
GROUP BY YEAR(Date), MONTH(Date)
ORDER BY Year, Month


--Total Revenue generated at previous Year--
SELECT
DATEADD(MONTH, -1, Date) AS Previous_Year,
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_Sales 
GROUP BY DATEADD(MONTH, -1, Date)
ORDER BY SUM(Amount * Boxes_Shipped) DESC


--Total Revenue generated by Country--
SELECT
Country,
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_sales
GROUP BY Country
ORDER BY Total_Revenue DESC

--Total Boxshipped by Country--
SELECT
Country,
COUNT(Boxes_Shipped) AS Count_of_Boxes_Shipped
FROM
Chocolate_sales
GROUP BY Country
ORDER BY Count_of_Boxes_Shipped DESC

--Product decreasing in Sales Revenue--
SELECT
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_sales
GROUP BY [Product]
ORDER BY SUM(Amount * Boxes_Shipped) ASC

--Product with low average Quantity--
SELECT
[Product],
AVG(Boxes_Shipped) AS Average_Boxes_Shipped
FROM
Chocolate_sales
GROUP BY [Product]
ORDER BY AVG(Boxes_Shipped) ASC

--Frequency Purchase by Sales Persons--
SELECT
Sales_Person,
COUNT (*) AS Frequency_Purchase
FROM
Chocolate_sales
GROUP BY Sales_Person
ORDER BY SUM(Amount * Boxes_Shipped) DESC


--Frequency Purchase by Sales Persons--
SELECT
Sales_Person,
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_sales
GROUP BY Sales_Person
ORDER BY SUM(Amount * Boxes_Shipped) DESC

--Average Amount of product from Total Revenue-- 
SELECT
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM 
Chocolate_sales
GROUP BY [Product]
HAVING SUM(Amount * Boxes_Shipped) >= 50000000
(SELECT 
AVG(Amount * Boxes_Shipped) AS Average_Total_Sales
FROM
Chocolate_Sales)

--Purchase Frequency--
SELECT
Sales_Person,
COUNT(*) AS Purchase_Frequency
FROM
Chocolate_Sales
GROUP BY Sales_Person
ORDER BY Purchase_Frequency DESC

--Ranking product by revenue--
SELECT
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue,
RANK() OVER(ORDER BY SUM(Amount * Boxes_Shipped)DESC) AS Ranked_Revenue
FROM
Chocolate_sales
GROUP BY [Product]

--Ranking revenue by month--
SELECT 
MONTH(Date) AS Monthly_Revenue,
SUM(Amount * Boxes_Shipped) AS Total_Revenue,
RANK() OVER(ORDER BY SUM(Amount * Boxes_Shipped)DESC) AS Ranked_Month
FROM
Chocolate_Sales
GROUP BY MONTH(Date)

--Ranked Monthly Revenue by countries
SELECT 
DISTINCT Country,
MONTH(Date) AS Sales_Month,
SUM(Amount * Boxes_Shipped) AS Total_Revenue,
RANK() OVER(PARTITION BY Country ORDER BY SUM(Amount * Boxes_Shipped)DESC) AS Ranked_Countries_by_Revenue
FROMb
Chocolate_Sales
GROUP BY Country, MONTH(Date)


--Using CTE to find the Monthly and Yearly Revenue--
WITH Monthly_sales AS
(
SELECT 
YEAR(Date) AS SalesYear,
MONTH(Date) AS SalesMonth,
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_Sales
GROUP BY 
YEAR(Date), MONTH(Date)
)
SELECT *
FROM Monthly_sales
ORDER BY SalesYear, SalesMonth


--Using CTE to find the Revenue Per Product--
WITH Product_Revenue AS
(
SELECT [Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_sales
GROUP BY [Product]
)
SELECT *
FROM Product_Revenue
ORDER BY Total_Revenue DESC


--Contribution Percentage of each product to total revenue--
SELECT
[Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue,
(SUM(Amount * Boxes_Shipped) * 100.0 / 
(SELECT SUM(Amount * Boxes_Shipped) 
FROM 
Chocolate_Sales)
    ) AS Contribution_Percentage
FROM Chocolate_Sales
GROUP BY [Product]
ORDER BY Contribution_Percentage,Total_Revenue

--This is the Product Revenue before Average--
WITH Product_Revenue AS
(
SELECT [Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_Sales
GROUP BY [Product]
)
SELECT *
FROM Product_Revenue
WHERE Total_Revenue >
(SELECT AVG(Total_Revenue) FROM Product_Revenue)
ORDER BY Total_Revenue DESC

--Ranked Revenue by Product--
WITH Product_Revenue AS
(
SELECT [Product],
SUM(Amount * Boxes_Shipped) AS Total_Revenue
FROM
Chocolate_Sales
GROUP BY [Product]
)
SELECT 
[Product],
Total_Revenue,
RANK() OVER(ORDER BY Total_Revenue DESC) AS Revenue_Rank
FROM 
Product_Revenue



